"""MEM — VLA long & short term memory (Mar 2026).

Two memory stores keep long-horizon tasks tractable without blowing up the
VLA's context window:

- **Short-term video memory:** rolling buffer of recent frames at a fixed
  fps. Resolves occlusions and short-term causality (e.g., where did the
  cup go).
- **Long-term language memory:** semantic summaries of completed subtasks,
  generated by an off-the-shelf LLM. Stored as `(subtask, summary, embedding)`
  triples; retrievable by cosine similarity against a query embedding.
  Lets the robot answer "did I already add salt?" without keeping raw images
  in context.

Paper: papers/2026-03-03_mem_vla-long-short-term-memory.pdf

Design choices:

- **Pluggable summarizer + embedder.** MEM doesn't bundle an LLM — the
  caller passes any ``Callable``. Defaults are deterministic (no network)
  so tests run offline. Production swaps in Anthropic / sentence-transformers /
  any other model.
- **Numpy under the hood.** Frames are stored as numpy arrays; embeddings
  are 1-D float32 vectors. This keeps MEM cheap to pickle, easy to inspect
  in notebooks, and decoupled from any deep-learning framework.
"""

from __future__ import annotations

import hashlib
import re
from collections import deque
from dataclasses import dataclass, field
from typing import Callable, Sequence

import numpy as np


# --- Pluggable interfaces ------------------------------------------------

SummarizerFn = Callable[[str, list[np.ndarray]], str]
"""(subtask, frames) -> single-sentence summary."""

EmbedderFn = Callable[[str], np.ndarray]
"""text -> (D,) float32 embedding."""


def default_summarizer(subtask: str, frames: list[np.ndarray]) -> str:
    """Deterministic no-LLM summarizer.

    Returns a short canonical string. Replace with an Anthropic / HF model
    in production by passing a different ``summarizer`` to MEM.
    """
    return f"completed subtask '{subtask}' over {len(frames)} frames"


def default_embedder(text: str, dim: int = 64) -> np.ndarray:
    """Deterministic hashing embedder — no network, no PyTorch.

    For each word in the text, hash to a bucket index and increment.
    Normalize to unit length. This is *not* semantic — it only matches
    queries that share words with stored summaries. For real semantic
    retrieval, swap in ``sentence-transformers`` or a similar model.
    """
    words = re.findall(r"[A-Za-z0-9]+", text.lower())
    if not words:
        return np.zeros(dim, dtype=np.float32)
    vec = np.zeros(dim, dtype=np.float32)
    for w in words:
        h = int.from_bytes(hashlib.blake2b(w.encode(), digest_size=8).digest(), "big")
        vec[h % dim] += 1.0
    norm = np.linalg.norm(vec)
    if norm > 0:
        vec /= norm
    return vec.astype(np.float32)


# --- Config + record types ----------------------------------------------


@dataclass
class MEMConfig:
    short_term_video_seconds: float = 8.0
    short_term_fps: int = 4
    long_term_max_summaries: int = 64
    summarizer_model: str = "claude-haiku-4-5-20251001"  # informational only
    embedding_dim: int = 64


@dataclass
class LongTermEntry:
    subtask: str
    summary: str
    embedding: np.ndarray
    t_start: float
    t_end: float


# --- Short-term video memory --------------------------------------------


class ShortTermVideoMemory:
    """Rolling buffer of recent frames, downsampled to ``short_term_fps``.

    The buffer keeps at most ``ceil(short_term_video_seconds * short_term_fps)``
    frames. Older frames are evicted FIFO. Frames are stored verbatim — no
    encoding — so callers can inspect them or hand them to a vision tower.
    """

    def __init__(self, config: MEMConfig) -> None:
        self.config = config
        self.max_frames = int(
            np.ceil(config.short_term_video_seconds * config.short_term_fps)
        )
        self._frames: deque[tuple[float, np.ndarray]] = deque(maxlen=self.max_frames)
        self._last_t: float | None = None

    def add(self, frame: np.ndarray, t: float) -> bool:
        """Add a frame at time ``t`` (seconds). Returns True if accepted.

        Skips frames that arrive faster than the configured fps so the
        buffer represents a *temporally uniform* slice. Caller may push
        every camera frame; MEM downsamples.
        """
        min_dt = 1.0 / self.config.short_term_fps
        if self._last_t is not None and (t - self._last_t) < min_dt - 1e-6:
            return False
        self._frames.append((float(t), np.asarray(frame)))
        self._last_t = t
        return True

    def recall(self) -> np.ndarray:
        """Stacked frames in chronological order, shape ``(T, *frame_shape)``.

        Returns an empty array if the buffer is empty.
        """
        if not self._frames:
            return np.empty((0,), dtype=np.float32)
        return np.stack([f for _, f in self._frames], axis=0)

    def timestamps(self) -> np.ndarray:
        return np.array([t for t, _ in self._frames], dtype=np.float32)

    def __len__(self) -> int:
        return len(self._frames)

    def clear(self) -> None:
        self._frames.clear()
        self._last_t = None


# --- Long-term language memory ------------------------------------------


class LongTermLanguageMemory:
    """Semantic summaries of completed subtasks with cosine-similarity recall.

    FIFO eviction past ``long_term_max_summaries``. Search is brute-force
    cosine over stored embeddings — fine up to a few thousand entries;
    swap in FAISS if you outgrow it.
    """

    def __init__(
        self,
        config: MEMConfig,
        summarizer: SummarizerFn | None = None,
        embedder: EmbedderFn | None = None,
    ) -> None:
        self.config = config
        self._summarize = summarizer or default_summarizer
        self._embed = embedder or (lambda t: default_embedder(t, dim=config.embedding_dim))
        self._entries: deque[LongTermEntry] = deque(maxlen=config.long_term_max_summaries)

    def add_subtask(
        self,
        subtask: str,
        frames: Sequence[np.ndarray],
        *,
        t_start: float,
        t_end: float,
    ) -> LongTermEntry:
        """Summarize and store a completed subtask."""
        frames_list = [np.asarray(f) for f in frames]
        summary = self._summarize(subtask, frames_list)
        embedding = self._embed(summary).astype(np.float32)
        entry = LongTermEntry(
            subtask=subtask,
            summary=summary,
            embedding=embedding,
            t_start=float(t_start),
            t_end=float(t_end),
        )
        self._entries.append(entry)
        return entry

    def recall(self, query: str, k: int = 5) -> list[LongTermEntry]:
        """Return up to ``k`` summaries ranked by cosine similarity to ``query``."""
        if not self._entries:
            return []
        q = self._embed(query).astype(np.float32)
        q_norm = np.linalg.norm(q)
        if q_norm == 0:
            return []
        q = q / q_norm
        scored = []
        for entry in self._entries:
            e_norm = np.linalg.norm(entry.embedding)
            if e_norm == 0:
                continue
            sim = float(q @ (entry.embedding / e_norm))
            scored.append((sim, entry))
        scored.sort(key=lambda pair: pair[0], reverse=True)
        return [entry for _, entry in scored[:k]]

    def __len__(self) -> int:
        return len(self._entries)

    def entries(self) -> list[LongTermEntry]:
        return list(self._entries)

    def clear(self) -> None:
        self._entries.clear()


# --- Top-level MEM facade ------------------------------------------------


@dataclass
class MEM:
    """Dual-memory store consumed by π₀.₇.

    The facade just composes the two stores. Callers typically:

    1. Per-step: ``mem.add_frame(frame, t)`` — fed every camera frame.
    2. On subtask completion: ``mem.add_subtask_summary(...)`` — let the
       LLM compress the elapsed video into one sentence.
    3. When the policy needs context: ``mem.recent_frames()`` for
       short-term, ``mem.recall(query)`` for long-term.
    """

    config: MEMConfig = field(default_factory=MEMConfig)
    summarizer: SummarizerFn | None = None
    embedder: EmbedderFn | None = None
    short_term: ShortTermVideoMemory = field(init=False)
    long_term: LongTermLanguageMemory = field(init=False)

    def __post_init__(self) -> None:
        self.short_term = ShortTermVideoMemory(self.config)
        self.long_term = LongTermLanguageMemory(
            self.config, summarizer=self.summarizer, embedder=self.embedder
        )

    def add_frame(self, frame: np.ndarray, t: float) -> bool:
        return self.short_term.add(frame, t)

    def recent_frames(self) -> np.ndarray:
        return self.short_term.recall()

    def add_subtask_summary(
        self,
        subtask: str,
        frames: Sequence[np.ndarray] | None = None,
        *,
        t_start: float,
        t_end: float,
    ) -> LongTermEntry:
        """Summarize a subtask. If ``frames`` is None, uses the short-term buffer."""
        if frames is None:
            frames = list(self.short_term.recall())
        return self.long_term.add_subtask(subtask, frames, t_start=t_start, t_end=t_end)

    def recall(self, query: str, k: int = 5) -> list[LongTermEntry]:
        return self.long_term.recall(query, k=k)

    def reset(self) -> None:
        self.short_term.clear()
        self.long_term.clear()
