"""MEM — VLA long & short term memory (Mar 2026).

Two memory stores keep long-horizon tasks tractable without blowing up the
VLA's context window:

- **Short-term video memory:** rolling buffer of recent frames used to
  resolve occlusions and short-term causality (e.g., where did the cup go).
- **Long-term language memory:** semantic summaries of completed subtasks,
  generated by an off-the-shelf LLM, used to answer questions like
  "did I already add salt?" without storing raw images.

Paper: papers/2026-03-03_mem_vla-long-short-term-memory.pdf
"""

from __future__ import annotations

from collections import deque
from dataclasses import dataclass, field


@dataclass
class MEMConfig:
    short_term_video_seconds: float = 8.0
    short_term_fps: int = 4
    long_term_max_summaries: int = 64
    summarizer_model: str = "claude-haiku-4-5-20251001"  # off-the-shelf LLM


@dataclass
class MEM:
    """Dual-memory store consumed by π₀.₇.

    TODO:
      - implement `add_frame(frame, t)` ring buffer
      - implement `summarize_subtask(subtask, frames)` via the LLM
      - implement `recall(query)` returning relevant summaries
      - serialize/deserialize for episode resumption
    """

    config: MEMConfig = field(default_factory=MEMConfig)
    short_term: deque = field(default_factory=deque)
    long_term: list[str] = field(default_factory=list)

    def add_frame(self, *args, **kwargs):
        raise NotImplementedError

    def summarize_subtask(self, *args, **kwargs):
        raise NotImplementedError

    def recall(self, *args, **kwargs):
        raise NotImplementedError
